spring:
  application:
    name: shop
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

api:
  v1: /api/v1

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY:}
    success-url: ${TOSS_SUCCESS_URL:}
    fail-url: ${TOSS_FAIL_URL:}